global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/nssf.log
  level: debug

nssf:
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80
      nsi:
        - uri: http://{{NRF_IP}}:80
          s_nssai:
            sst: 1
            sd: 000001
