global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/pcf.log
  level: {{LOG_LEVEL}}

db_uri: {{DB_URI}}

pcf:
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80

# Locally configured policy
policy:
  - plmn_id:
      mcc: {{MCC}}
      mnc: {{MNC}}
    slice:
      - sst: {{SST}}
        sd: {{SD}}
        default_indicator: true
        session:
          - name: internet
            type: 3
            ambr:
              downlink:
                value: 1
                unit: 3
              uplink:
                value: 1
                unit: 3
