global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/smf.log
  level: debug

smf:
  gtpu:
    server:
      - address: {{MY_IP}}
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80
  pfcp:
    server:
      - address: {{MY_IP}}
    client:
      upf:
        - address: {{UPF_IP}}
  session:
    - subnet: 10.45.0.1/16
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
