global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/smf.log
  level: {{LOG_LEVEL}}

smf:
  # 4G 
  ## this `gtpc`  block to enable the PGW-C S5-C interface on UDP 2123
  gtpc:
    server:
      - address: {{MY_IP}}
  freeDiameter: /tmp/config/smf.conf

  gtpu:
    server:
      - address: {{MY_IP}}
  # 5G
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80
  pfcp:
    server:
      - address: {{MY_IP}}
    client:
      upf:
        - address: {{UPF_IP}}
  session:
    - subnet: {{UE_SUBNET}}
      gateway: {{UE_GATEWAY}}
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
