global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/udm.log
  level: debug

udm:
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80
