global:
  max:
    ue: 1024

logger:
  file: 
    path: /open5gs/logs/udr.log
  level: {{LOG_LEVEL}}

db_uri: {{DB_URI}}

udr:
  sbi:
    server:
      - address: {{MY_IP}}
        port: 80
    client:
      nrf:
        - uri: http://{{NRF_IP}}:80
