global:
  max:
    ue: 1024

logger:
  file: /open5gs/logs/nssf.log
  level: info

nssf:
  sbi:
    server:
      - address: {{MY_IP}}
        port: 7777
    client:
      nrf:
        - uri: http://{{NRF_IP}}:7777
      nsi:
        - uri: http://{{NRF_IP}}:7777
          s_nssai:
            sst: 1
            sd: 000001
