global:
  max:
    ue: 1024

logger:
  file: /open5gs/logs/udr.log
  level: info

db_uri: mongodb://mongodb:27017/open5gs

udr:
  sbi:
    server:
      - address: 10.9.0.20
        port: 7777
    client:
      nrf:
        - uri: http://10.9.0.10:7777
