global:
  max:
    ue: 1024

logger:
  file: /open5gs/logs/upf.log
  level: info

upf:
  pfcp:
    server:
      - address: {{MY_IP}}
  gtpu:
    server:
      - address: {{MY_IP}}
  session:
    - subnet: 10.45.0.1/16
      dnn: internet
      dev: ogstun
